apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    name: parse-server-5bbdaa00260a53029f294478-subb
  name: parse-server-5bbdaa00260a53029f294478-subb
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/parse-server-5bbdaa00260a53029f294478-subb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: parse-server-5bbdaa00260a53029f294478-subb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: parse-server-5bbdaa00260a53029f294478-subb
    spec:
      containers:
      - command:
        image: registry.gitlab.com/appgain.io/appgain.appbackend/parse-server-lite
        imagePullPolicy: Always
        name: parse-server-5bbdaa00260a53029f294478-subb
        ports:
        - containerPort: 1337
          name: parse-port
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /parse-server/cloud
          name: parse-server-5bbdaa00260a53029f294478-subb-cloud
        - mountPath: /parse-server/cert
          name: parse-server-5bbdaa00260a53029f294478-subb-cert
        - mountPath: /parse-server/conf
          name: parse-server-5bbdaa00260a53029f294478-subb-conf
        - mountPath: /parse-server/logs
          name: parse-server-5bbdaa00260a53029f294478-subb-logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: parse-server-5bbdaa00260a53029f294478-subb-cloud
        nfs:
          path: /appbackend/5bbdaa00260a53029f294478/subb/cloud
          server: efs.appgain.internal
      - name: parse-server-5bbdaa00260a53029f294478-subb-cert
        nfs:
          path: /appbackend/5bbdaa00260a53029f294478/subb/cert
          server: efs.appgain.internal
      - name: parse-server-5bbdaa00260a53029f294478-subb-conf
        nfs:
          path: /appbackend/5bbdaa00260a53029f294478/subb/conf
          server: efs.appgain.internal
      - name: parse-server-5bbdaa00260a53029f294478-subb-logs
        nfs:
          path: /appbackend/5bbdaa00260a53029f294478/subb/logs
          server: efs.appgain.internal
status: {}
